CREATE TABLE IF NOT EXISTS puzzles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  puzzle_id TEXT NOT NULL UNIQUE,
  fen TEXT NOT NULL,
  moves TEXT NOT NULL,
  rating INTEGER,
  themes TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
); 