name: Fix Stockfish Permissions

on:
  push:
    branches:
      - main

jobs:
  fix-perms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x public/engine/stockfish
      - run: git config --global user.email "ruturajvishwamitre@gmail.com"
      - run: git config --global user.name "RutuVishwa"
      - run: git add public/engine/stockfish
      - run: git commit -m "Set Stockfish binary as executable [skip ci]" || echo "No changes to commit"
      - name: Push changes
        run: git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}